apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web
 name: events-web-v3
spec:
 replicas: 1
 selector:
   matchLabels:
     app: events-web
     ver: v3.0
 template:
   metadata:
     labels:
       app: events-web
       ver: v3.0
   spec:
     containers:
      - image: srpillai/e-web:v3
        name: events-web
        ports:
        - containerPort: 8080
        env:
        - name: SERVER
          value: "http://events-api-svc:8082"
