apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web
 name: events-web
spec:
 replicas: 1
 selector:
   matchLabels:
     app: events-web
     ver: v1.0
 template:
   metadata:
     labels:
       app: events-web
       ver: v1.0
   spec:
     containers:
      - image: 874954573048.dkr.ecr.us-east-1.amazonaws.com/e-web:v1
        name: events-web
        ports:
        - containerPort: 8080
        env:
        - name: SERVER
          value: "http://events-api-svc:8082"
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: events-web-svc
 name: events-web-svc
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: events-web
  #  ver: v1.0
 type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: events-web-hpa
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: events-web
    minReplicas: 2
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
